### ISSUE TITLE
Update to 0.4.1 hangs because of rename

### ISSUE THREAD

**Issue by r0ckarong** [SpectralKH/chester-syntax#3]
You renamed the package in this commit:

https://github.com/SpectralKH/chester-syntax/commit/a8002f63bf32d6559e067ac37789f81530d4eb73#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

If you have the old version installed, you will see an update available for "chester-syntax" and be able to install. After another check the same update will pop up again.

The only way I have managed to make this work again is to uninstall 'chester-syntax' and 'chester-kh-syntax' and only reinstall the latter.

**Comment by probablykasper** [comment]
Thank you very much for the info! :) I will not change it back though, in case this is fixed in the future and I am able to give [chester-atom-syntax](https://github.com/csutter/chester-atom-syntax) that name. I will add some notice about this not being maintained.

**Comment by amit-feldman** [comment]
I can confirm it happens with version 0.4.2 as well.

**Comment by probablykasper** [comment]
@icsvortex666 Yeah, I just added a notice saying it's no longer maintained. Get [chester-atom-syntax](https://github.com/csutter/chester-atom-syntax).
